n1 = input("escreva algo aqui: ")
print('o tipo desse valor é: {}'.format(type(n1)))
print('é alfanumerico? {}'.format(n1.isalnum()))
print('é uma palavra? {}'.format(n1.isalpha()))
print('é um digito? {}'.format(n1.isdigit()))
print('está em minuscula? {}'.format(n1.islower()))
print('é decimal? {}'.format(n1.isdecimal()))
print('é um identificador valido? {}'.format(n1.isidentifier()))
print('é um numero? {}'.format(n1.isnumeric()))
print('está vazia? {}'.format(n1.isprintable()))
print('só tem espaço? {}'.format(n1.isspace()))
print('está capitalizada? {}'.format(n1.istitle()))
print('está em maiusculas? {}'.format(n1.isupper()))
